pipeline:
  build:
    image: ensime/ensime:v2.x-cache
    pull: true
    commands:
      - host `curl -s http://httpbin.org/ip | jq -r '.origin'` || true ;
      - git log | head -n 20 ; git fetch -q --tags
      - cask pkg-file ;
        cask install ;
        cask build ;

